version: '3.8'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5000:5000
    command: python server.py run -h 0.0.0.0
    volumes:
      - ./uploads:/tmp/app/uploads
    environment:
      - DEBUG=1